### ISSUE TITLE
PS scripts fail on newly installed Win11

### ISSUE THREAD

**Issue by alexmcwi** [Lateralus138/hosts-compression-scripts#1]
NEVERMIND. I made a mistake downloading the script (right-clicked on the link and then "save as" instead of opening the link to the script and downloading the actual code.

Hi,

First of all, thanks for going through the trouble of creating this script, however, for some reason I can't get it to work (granted, I'm far from being a PS expert, so please bear with me).

I wonder if I'm missing something.

It would be great if you also shared an exe version as well. Not everybody has VS installed, let alone hours to tinker with it if things don't work as they're supposed to (e.g. me).

Thanks!

I set the execution policy to unrestricted, as your readme suggests, but I'm getting this:

`PS D:\temp> .\compress_hosts.ps1 -InputFile 'D:\temp\hosts 2024-02' -OutputFile d:\temp\compressed
At D:\temp\compress_hosts.ps1:41 char:60
+ ... script type="application/json" id="client-env">{"locale":"en","featur ...
+                                                             ~~~~~
Unexpected token ':"en"' in expression or statement.
At D:\temp\compress_hosts.ps1:41 char:65
+ ... cript type="application/json" id="client-env">{"locale":"en","feature ...
+                                                                 ~
Missing argument in parameter list.
At D:\temp\compress_hosts.ps1:41 char:496
+ ... key_shortcuts_in_inputs","custom_inp","remove_child_patch"]}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At D:\temp\compress_hosts.ps1:230 char:84
+ ... tion/json" data-target="react-partial.embeddedData">{"props":{}}</scr ...
+                                                                 ~
Unexpected token ':' in expression or statement.
At D:\temp\compress_hosts.ps1:230 char:88
+ ... /json" data-target="react-partial.embeddedData">{"props":{}}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At D:\temp\compress_hosts.ps1:266 char:205
+ ... ink Button--medium Button d-lg-none color-fg-inherit p-1">  <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At D:\temp\compress_hosts.ps1:289 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
At D:\temp\compress_hosts.ps1:487 char:13
+       CI/CD &amp; Automation
+             ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\temp\compress_hosts.ps1:562 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
At D:\temp\compress_hosts.ps1:577 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

PS D:\temp>`

Even running the script with no parameters yields the same results:

`PS D:\temp> .\compress_hosts.ps1
At D:\temp\compress_hosts.ps1:41 char:60
+ ... script type="application/json" id="client-env">{"locale":"en","featur ...
+                                                             ~~~~~
Unexpected token ':"en"' in expression or statement.
At D:\temp\compress_hosts.ps1:41 char:65
+ ... cript type="application/json" id="client-env">{"locale":"en","feature ...
+                                                                 ~
Missing argument in parameter list.
At D:\temp\compress_hosts.ps1:41 char:496
+ ... key_shortcuts_in_inputs","custom_inp","remove_child_patch"]}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At D:\temp\compress_hosts.ps1:230 char:84
+ ... tion/json" data-target="react-partial.embeddedData">{"props":{}}</scr ...
+                                                                 ~
Unexpected token ':' in expression or statement.
At D:\temp\compress_hosts.ps1:230 char:88
+ ... /json" data-target="react-partial.embeddedData">{"props":{}}</script>
+                                                                 ~
The '<' operator is reserved for future use.
At D:\temp\compress_hosts.ps1:266 char:205
+ ... ink Button--medium Button d-lg-none color-fg-inherit p-1">  <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At D:\temp\compress_hosts.ps1:289 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
At D:\temp\compress_hosts.ps1:487 char:13
+       CI/CD &amp; Automation
+             ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At D:\temp\compress_hosts.ps1:562 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
At D:\temp\compress_hosts.ps1:577 char:45
+             <ul class="list-style-none f5" >
+                                             ~
Missing file specification after redirection operator.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken

PS D:\temp>
`

**Comment by Lateralus138** [comment]
Since you've closed this I might assume you've solved the issue, if so I'm glad to hear it (as I haven't had a chance to look into it yet). As for an exe version there already is one and it's stated in the [README](https://github.com/Lateralus138/hosts-compression-scripts/README.md) at the beginning of this repository:
![Screenshot 2024-02-17 144000](https://github.com/Lateralus138/hosts-compression-scripts/assets/21045862/d8a2ed2f-3d54-4c73-88c8-f63f82bc55f8)
which I definitely recommend as it's immensely faster than then the scripts.
The command line exe version can be found here: [https://github.com/Lateralus138/hosts-compress-windows](https://github.com/Lateralus138/hosts-compress-windows)

**Comment by alexmcwi** [comment]
Hi Ian,

Yes. No issue at all. Only my failure to pay more attention to what I was doing.

The PS script is pretty fast on my computer (i7-something newish), so it only took about a minute, but most importantly, it solved the issue I was having (no access to netbios shares or Taskbar on Win11 until the DNS client would settle down.

One often overlooked benefit of an aggressive hosts file is that it prevents ads, some of which are horribly resource-hungry, from eating up the CPU.

Amazingly, I looked at that link you circled a bunch of times and somehow missed the link to the actual releases on the right column.

Here's the direct link, in case someone else has an attack of the dumbs as bad as mine today:

https://github.com/Lateralus138/hosts-compress-windows/releases

Thanks!

Alex

**Comment by Lateralus138** [comment]
I'm glad to hear I could help! Just so you're aware the actual exe is almost instantaneous (around 500ms - half a second).
